[project]
name = "uw-jekyll-theme"
version = "0.1.0"
description = "A UW-Madison theme for a Jekyll based academic website"
authors = ["Matthew Feickert <matthew.feickert@wisc.edu>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tasks]
# Need to use '--user-install' as using pixi instead of rbenv
install = """
gem install --user-install bundle && \
bundle install
"""

check = "bundle exec rake check"

build = "bundle exec rake build"

serve = "bundle exec rake serve"

clean = "bundle exec rake clean"

clobber = "bundle exec rake clobber"

[dependencies]
ruby = ">=3.3.3,<4"
compilers = ">=1.7.0,<2"
imagemagick = ">=7.1.1_36,<8"
